### ISSUE TITLE
Should Parse throw the exception?

### ISSUE THREAD

**Issue by AlexGhiondea** [AlexGhiondea/CommandLine#40]
Right now, calling `Parse` will return a null object if something bad happened during the parse.

An error message is displayed to the user that contains the exception.

However, there isn't a good way to catch the exception that was begin thrown from the parser.

Thoughts?

/cc @lucyainsworth @safern @hanabi1224

**Comment by lucyainsworth** [comment]
Seems like Parse should throw the exception while TryParse should catch it.  Not a big deal for my purposes, but this would follow alot of other c# library conventions with TrySomething vs Something.

**Comment by AlexGhiondea** [comment]
I agree -- for some reason when I originally developed this, Parse would still not throw.

I think I will change the 1.6 release (where support for color was going to go) to a 2.0 release and also make this change to Parse and TryParse.

Fun fact -- TryParse does throw in some cases even now. 😞

**Comment by safern** [comment]
Yes I agree that Parse should throw rather than returning a null object. I think that follows what other libraries do, specially when you have both `Parse` and `TryParse` which tells people, `Parse` will fail if it can't parse it and throw, `TryParse` will just return false, then you can do whatever you want when false is returned.

**Comment by AlexGhiondea** [comment]
The question then becomes — should Parse / TryParse log the errors to the console and display the help message?

I am thinking of the following:
- Parse and TryParse will log just like today to the console
- there will be an option on the Parser to configure this behavior
- TryParse will be made to not throw (not like today) :)
- Parse will log to the console (if enabled) and then rethrow the exception.


How does this sound?

**Comment by safern** [comment]
That sounds good to me, except for `Parse and TryParse will log just like today to the console`. 

I'm hesitant on whether `TryParse` should log to the console. Maybe this could be an optional parameter added to `TryParse` in order to tell it to log to the console or not? 

The reason why I'm hesitant is because if I'm using `TryParse` I want to do my own handling of errors and probably if it returns false, I'll do that myself... Maybe there could be a `TryParse` override that has an out parameter to return the error message so that the user can do something with it. I think `TryParse` should be silent and let the caller handle the error by checking on the result itself.

**Comment by AlexGhiondea** [comment]
So you're saying that nothing should be logged to the console? 

One of the reasons for building this was that I was hoping to avoid having the callers require to do something with the result of the call to the library.

I think it would be good to have some way to configure that (maybe a different overload is the way to go -- instead of a configuration class).

I'll have to prototype that :).

**Comment by safern** [comment]
I'm referring only to `TryParse`.

But actually, having it log to the console by default if it failed to parse makes sense, and then having a way to opt-out from that behavior makes more sense.

**Comment by AlexGhiondea** [comment]
This is done!
